services:
  comfyui:
    image: yanwk/comfyui-boot:cu128-slim
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - "./mnt/storage:/root"
      - "./mnt/models:/root/ComfyUI/models"
      - "./mnt/input:/root/ComfyUI/input"
      - "./mnt/output:/root/ComfyUI/output"
      - "./mnt/custom_nodes:/root/ComfyUI/custom_nodes"
    environment:
      - TZ=Europe/Istanbul
      - CLI_ARGS=--listen --port 8188
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
